[package]
name = "web_dioxus"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dioxus = { version = "0.1.8", features = ["web"] }
#dioxus-web = "0.0.5"
#wasm-bindgen = "0.2.78"