name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install trunk
      run: cargo install trunk
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Trunk Check
      #uses: trunk-io/trunk-action@v0.4.0-beta
      uses: jetli/trunk-action@v0.1.0
    - name: Trunk build
      run: trunk build
    - name: Trunk tests
      run: trunk serve
