name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install trunk
      #run: cargo install trunk
      uses: jetli/trunk-action@v0.1.0
    - name: Add web assembly 
      run: rustup target add wasm32-unknown-unknown
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Trunk.toml build
      run: trunk build --release
    - name: Trunk.toml tests
      run: trunk serve
